version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/books
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
 